language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run test
- npm run build
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  api_key:
    secure: yfe7ZfG3NLAqPQ8Up+NH48cZsN5sNSwtV1BTpYpU7TBejVB0UvMVZdXzXR/TS4l9NIjpXoHHk0rc3JOyhw4tM8Ywn5L8F3vNju9gQLYvGhpEpzvUKVWjC1M3kerpNfDwefEk3tQIHe8AMjR5AnRZMFlC16y5KVscGgz7KxNKmeLwCNIUUUxa28xufKb7EM8J9pxjac3lVE+btvPVRfRdGWHyTtmlSUnbz73V5N/MECDpDMUSaGaxFdqfDUmjZ3a8qJX4tRt/AdPkL4CQvAZXMrpjdg+CcMifeT8MJnHP3d0kPUJ4uWXgcr7m54Xbo9s8jqa4/zrcwb40XjlDIFuArsydGUlQkcqgTM0DGOr3ubUYoRSAZFsInMEmgxfVR0KP7pOUMzzu4+I4UzC3nACIS9ZND6zn/C9yxcJLA3qYFMtnqqRCH6SUR5pOfjtE+QWOe5XIOfiO643KfSRYWeO3bfJQL0bVULyvOd0Odf1B9p3xukCRbZR0xTRqGDJmB2w0X28WFoB62vLGgqW+CHnjNVQ14dcOFeteyA0R507ijQT+WrOl0rQJsr6Je2QbIGYMWwVVUWIHqs0a7/J94xNKOnaVATxwWxM02HZN60z3TZxItObZmGaijjYN314T0CU5VtIwnEWfqOzwE2KaknSr7K9Vgpw/Le2XAatWgyeUaAM=
  on:
    branch: master
notifications:
  slack:
    secure: rBmhq88dw0x2ym4/2IeuzsvYsqYaAgrIeNsiROfOAp13tKavI+pYJkJZwdFRtGcKaTTvurbYJrkpmZaM9SuDmrL1Bq2NUMbsRZIfLiJv/yCD9Ua5Bi/Sbt6Mpi5MtrBEponXSIjNQUkTIS3rQKc3AVX8ndvR1ZZGS1oqjlDANiBP7LVraAVyyCw4C7PmCFnRRZ/p/De0DN5opeLkdD30+qcULj+f703+k/6i2GMnD3wN/5b94q4D+Mbs19Ev54rrRisBCaVMJBOfsA3Chkw8Utyt3KjXoogZvqMP/S2vyhF6rjtpvLBwUqaggLoRC3DFj3i5hUM9Xi28O6NZ2bY7YDMdGdgWFuYUy+OcQyMFpCJKu+G8skuso/z/9Z/YSpHk93MmwByeywon87AcoTYPdVNF7CE1iqRPY996vKLwM45CFW0lsGkyRKmzMCwKX2Mz+VhuKzMrqGIm2s5TgUQXvqFxvD1eDDCbd5jL0I4bZBiZlAHLVAsegaOXpRMvFB4hVvz+qba6HsaPh50wUB5KkO0xhYAu4AYYP4o6+lycF1xgZ9ypqjzuDCZrAM9eIvxl+JIV0zWuWMTG4xuOwUth0ROfbQ4jyqcPLhOkRjP8G/PhcaDnlISrdmrHQxzZmLbx693mI7dxnN+1xwxOtKul2vVGXa4rr1RSX4V/uN8OYMo=
