language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: inovakov@gmail.com
  api_key:
    secure: BiLdHYrvGbPxMRDCBNewi4eSVIBO9qJS1M66VXvljN7aaGTGXHkHh7TH1rLTTotd1OuBAa9fGD9DfiH1QCec1c2a/qJUSYYEv2YzWehKpNMQckEuKNCsinFe/rFZ7Pzvm+A4JmTtE+oXZitqaKVyTl9ISuq61YlexONMalaKhjRtbzNdZaX6CoX5skxo6SHlpMUPOV13y3B8khLNaoY6VceaYl/2juyrgCW2ZDJt2O9vqSsdvlJfcioLRENOAY3vWK+6Dp2qe/k5K6gFxQFScULD1KsemirMemcQ+l7NimDA1QvQe1AuRsBL5HD53AnsZ/ZGkWX+rK7cI1IEfL8unQziXzCzuECjThgz8qShHBFpeOQDuAmFqjvtYF72jVSIMjiWfSE1ez/vpDO+dGeJ1WMhZv6dyFCytE8gQFjQYhDOiN5mtFHz+i2un9vix9nMmcrgErJRijMOkgSfbKE8NCuBSM1pu5LkpapH0ggSMwD+x2PX7QWZh+fBO6pASrKuAJXFALuuYLYeCJ88GT3Bq4JNzU0lcjdwksAv+4I5wAtaau2BQdUB1POSPgESMtYbIJlW8uaylnNkytB/m04BSVmz2lWwR3XZ0On8pIKVWJC1/K/jS5rs8O30JhPu6flvH2Y49De2AjwSVaC/AGGUWxoIlkwPL741teS2mJhUt2o=
  on:
    branch: master
notifications:
  slack:
    secure: rBmhq88dw0x2ym4/2IeuzsvYsqYaAgrIeNsiROfOAp13tKavI+pYJkJZwdFRtGcKaTTvurbYJrkpmZaM9SuDmrL1Bq2NUMbsRZIfLiJv/yCD9Ua5Bi/Sbt6Mpi5MtrBEponXSIjNQUkTIS3rQKc3AVX8ndvR1ZZGS1oqjlDANiBP7LVraAVyyCw4C7PmCFnRRZ/p/De0DN5opeLkdD30+qcULj+f703+k/6i2GMnD3wN/5b94q4D+Mbs19Ev54rrRisBCaVMJBOfsA3Chkw8Utyt3KjXoogZvqMP/S2vyhF6rjtpvLBwUqaggLoRC3DFj3i5hUM9Xi28O6NZ2bY7YDMdGdgWFuYUy+OcQyMFpCJKu+G8skuso/z/9Z/YSpHk93MmwByeywon87AcoTYPdVNF7CE1iqRPY996vKLwM45CFW0lsGkyRKmzMCwKX2Mz+VhuKzMrqGIm2s5TgUQXvqFxvD1eDDCbd5jL0I4bZBiZlAHLVAsegaOXpRMvFB4hVvz+qba6HsaPh50wUB5KkO0xhYAu4AYYP4o6+lycF1xgZ9ypqjzuDCZrAM9eIvxl+JIV0zWuWMTG4xuOwUth0ROfbQ4jyqcPLhOkRjP8G/PhcaDnlISrdmrHQxzZmLbx693mI7dxnN+1xwxOtKul2vVGXa4rr1RSX4V/uN8OYMo=
