language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm test
- npm build
deploy:
  provider: npm
  email: TrdelnikSquad@cimpress.com
  api_key:
    secure: VxWfL0Ms8Dr44leR/ZFU2Gr29oFm6YGegF1huAeEAiXzPiWzPG9cTKVDR/D4xTsLtclyLa+rG7fDGEbZdlIuTfQHUme4PMHR6KcrXvCjrJvcNhVw/n0uSEKRkTGIlP1q2+itU2ISfPYtiplQk1QO2IffCJtlwVha48phn1oh1xvFGf5RSHJcAo9etA+Fc3PauAyDMm3zZP3saNWUbDnVIFstswjlY+eKvWi9q+/LHqO7zDfy4+InMahNFYUbhgTi6GEKQzy/fctacdJ2e43Pq9su51+gDjE/UDwwswxBzdSkl0bpIgW6T6pZv8o2upS1kh+t3tGsYm9RhSerGgJiIjKZhpa4aKUZYjm/SNlmrG/8Sw7+3sdxRg0JeIadAt4XCQVF0F69kyXTIrcFjkQyVDSSLcsvy9T61a4PpVrw34srIam7WOoyd7XhSfBkIngwsaoDKyeayy9tu852KSFHQxmq7P0OjKwM37p2kI6RARsM3pLQqvb/GB5RTUUk9230wcMSKyPIJPfI2Vx1J/3cEf/ecoHgNZySFJ3QXZgaV0aHV3X5SWpFYUL+6nWrer9SOP90I+wcqB4v3VDVTGCr+zqvS+PQxAHnula4AjtkGTNiF+PGi6PyM141iAQv0gMtvTbNWurXju6BRuTNygHKd8QWAXQtKkcFLzpCyqCKsds=
  on:
    branch: master
notifications:
  slack:
    secure: rBmhq88dw0x2ym4/2IeuzsvYsqYaAgrIeNsiROfOAp13tKavI+pYJkJZwdFRtGcKaTTvurbYJrkpmZaM9SuDmrL1Bq2NUMbsRZIfLiJv/yCD9Ua5Bi/Sbt6Mpi5MtrBEponXSIjNQUkTIS3rQKc3AVX8ndvR1ZZGS1oqjlDANiBP7LVraAVyyCw4C7PmCFnRRZ/p/De0DN5opeLkdD30+qcULj+f703+k/6i2GMnD3wN/5b94q4D+Mbs19Ev54rrRisBCaVMJBOfsA3Chkw8Utyt3KjXoogZvqMP/S2vyhF6rjtpvLBwUqaggLoRC3DFj3i5hUM9Xi28O6NZ2bY7YDMdGdgWFuYUy+OcQyMFpCJKu+G8skuso/z/9Z/YSpHk93MmwByeywon87AcoTYPdVNF7CE1iqRPY996vKLwM45CFW0lsGkyRKmzMCwKX2Mz+VhuKzMrqGIm2s5TgUQXvqFxvD1eDDCbd5jL0I4bZBiZlAHLVAsegaOXpRMvFB4hVvz+qba6HsaPh50wUB5KkO0xhYAu4AYYP4o6+lycF1xgZ9ypqjzuDCZrAM9eIvxl+JIV0zWuWMTG4xuOwUth0ROfbQ4jyqcPLhOkRjP8G/PhcaDnlISrdmrHQxzZmLbx693mI7dxnN+1xwxOtKul2vVGXa4rr1RSX4V/uN8OYMo=
