language: node_js
node_js:
- '6'
install:
- npm install
script:
- npm run test
- npm run build
deploy:
  skip_cleanup: true
  provider: npm
  email: TrdelnikSquad@cimpress.com
  api_key:
    secure: U3FDggvRHqMO1UWtIsQR0mZ0NRqETVmfMmxVW+uptQYjVHj//c3EXox0TFFb9dpXal8DuyMk1W9RkltANACNKWqInxpkBp+aE1aOAvVjzUBZOBMoi4ubfuV2TMgTxpUs8RH5m6pdDXA3ufJEBDv3ec7WD8gT9luU88ubefjr1MvCp8O0v1wqyc2Oxo9bqIIj8dS/6MkyZD8baCDIpQC+HhSez4I8WeKRqpOCRtaEu4nFm5t4pObGHrPgubvN5N0kolOfNyNTWVx1drqevcFjbC8TQVRb3bdBwfW+MlRyZZK80unidFAFLF2KOEmS9lHxZDI+f+wKYYchd3/b3zpVj0yQTHf3w3JBRySq1qH8QuHJuY7vpNQ1ePhVIioNAPnPeZBOK+noRwD6erHqBB/OJR1KryTt9s5CUDz4MWHdKskXRAepPAySVWIVz6GlGm4fvG0plM5AezQisx+nfSo66J3Io3DIOyoBuGJBoQZCg8bpmf21QFtsQBH8wqmczVy5K8KT9wH8duaHCNzdtXdNb5zG47GDZgFjQb00BE7v5oC5U5nCtDxU/MeCKGCZ6Is1KYzXHsCpp72gceBU4VngdPWrcPXlQez2w7tqeaQ9k8OtAYMAzN4UPcv/8JbPL9QUYp1yVfz1CTE6UtkgQdZzQ2efNhYjzVXn4YA4ea7lmOw=
  on:
    branch: master
notifications:
  slack:
    secure: rBmhq88dw0x2ym4/2IeuzsvYsqYaAgrIeNsiROfOAp13tKavI+pYJkJZwdFRtGcKaTTvurbYJrkpmZaM9SuDmrL1Bq2NUMbsRZIfLiJv/yCD9Ua5Bi/Sbt6Mpi5MtrBEponXSIjNQUkTIS3rQKc3AVX8ndvR1ZZGS1oqjlDANiBP7LVraAVyyCw4C7PmCFnRRZ/p/De0DN5opeLkdD30+qcULj+f703+k/6i2GMnD3wN/5b94q4D+Mbs19Ev54rrRisBCaVMJBOfsA3Chkw8Utyt3KjXoogZvqMP/S2vyhF6rjtpvLBwUqaggLoRC3DFj3i5hUM9Xi28O6NZ2bY7YDMdGdgWFuYUy+OcQyMFpCJKu+G8skuso/z/9Z/YSpHk93MmwByeywon87AcoTYPdVNF7CE1iqRPY996vKLwM45CFW0lsGkyRKmzMCwKX2Mz+VhuKzMrqGIm2s5TgUQXvqFxvD1eDDCbd5jL0I4bZBiZlAHLVAsegaOXpRMvFB4hVvz+qba6HsaPh50wUB5KkO0xhYAu4AYYP4o6+lycF1xgZ9ypqjzuDCZrAM9eIvxl+JIV0zWuWMTG4xuOwUth0ROfbQ4jyqcPLhOkRjP8G/PhcaDnlISrdmrHQxzZmLbx693mI7dxnN+1xwxOtKul2vVGXa4rr1RSX4V/uN8OYMo=
